# Generated by Django 4.1 on 2022-10-18 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAdmin', models.CharField(max_length=60)),
                ('correo1', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLibro', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('capitulos', models.IntegerField()),
                ('categoria', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_punlicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
